import { useEffect, useState } from 'react';
import { Activity, AlertTriangle, Check, CircleDollarSign, Code2, Copy, Eye, Megaphone, Search, Settings2, ShieldCheck, Trash2, Users, Wallet, X } from 'lucide-react';

type User = { id: number; name: string; username: string; avatar: string; advertiserBalance: number; earnedBalance: number; status: 'نشط' | 'محظور'; bannedBySystem?: boolean; joinedAt: string; lastLogin: string; lastActive: string; invitedBy: string };
type Row = { id: string; userId?: number; amount?: number; createdAt?: string; status?: string; [key: string]: any };
type State = { users: User[]; deposits: Row[]; withdrawals: Row[]; campaigns: Row[]; proofs: Row[]; ads: Row[]; suspicious: Row[]; settings: Record<string, any>; reports: Row[] };
const KEY = 'vidreward.admin.preview.v1';
const proofMock = `data:image/svg+xml,${encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="800" height="500"><rect width="100%" height="100%" fill="#e9eef8"/><rect x="120" y="72" width="560" height="356" rx="28" fill="#fff"/><rect x="155" y="112" width="84" height="84" rx="24" fill="#edf3ff"/><path d="M179 154h36M197 136v36" stroke="#1557ee" stroke-width="8" stroke-linecap="round"/><rect x="268" y="118" width="340" height="16" rx="8" fill="#d8e1f2"/><rect x="268" y="150" width="240" height="12" rx="6" fill="#e9eef8"/><rect x="155" y="238" width="450" height="20" rx="10" fill="#e9eef8"/><rect x="155" y="276" width="390" height="20" rx="10" fill="#e9eef8"/><rect x="155" y="344" width="156" height="42" rx="12" fill="#1557ee"/><text x="333" y="371" font-family="sans-serif" font-size="17" fill="#52627e">DEMO PROOF IMAGE</text></svg>')}`;
const seed: State = {
 users: [
  { id: 610241, name: 'ليان السالمي', username: 'layan_demo', avatar: 'لس', advertiserBalance: 18.5, earnedBalance: 2.38, status: 'نشط', joinedAt: '2025-02-11', lastLogin: '2025-03-08 09:42', lastActive: 'قبل 4 دقائق', invitedBy: '—' },
  { id: 610258, name: 'عمر الراشد', username: 'omar_sample', avatar: 'عر', advertiserBalance: 0, earnedBalance: 0.74, status: 'نشط', joinedAt: '2025-02-18', lastLogin: '2025-03-08 08:16', lastActive: 'قبل 22 دقيقة', invitedBy: '610241' },
  { id: 610309, name: 'نور حمدان', username: 'nour_demo', avatar: 'نح', advertiserBalance: 43, earnedBalance: 5.12, status: 'نشط', joinedAt: '2025-02-26', lastLogin: '2025-03-07 19:30', lastActive: 'أمس', invitedBy: '610258' },
  { id: 610411, name: 'سامي فؤاد', username: 'sami_preview', avatar: 'سف', advertiserBalance: 2.2, earnedBalance: 0.16, status: 'محظور', bannedBySystem: true, joinedAt: '2025-03-01', lastLogin: '2025-03-06 12:01', lastActive: 'منذ يومين', invitedBy: '—' },
 ],
 deposits: [
  { id: 'DEP-4821', userId: 610241, method: 'Stars', amount: 12, createdAt: '2025-03-08 09:14', memoTag: 'VR-610241-A', txId: 'TG-ST-89021', status: 'ناجح' },
  { id: 'DEP-4818', userId: 610309, method: 'USDT', amount: 31, createdAt: '2025-03-07 17:05', memoTag: 'VR-610309-B', wallet: '0x81…b029', txId: '0xa21f…', status: 'فاشل', reason: 'لم يصل التحويل إلى الشبكة المحددة' },
 ],
 withdrawals: [
  { id: 'WDR-2064', userId: 610258, amount: 1.24, method: 'Binance', destination: '684291037', memoTag: 'vr-omar', createdAt: '2025-03-08 08:50', status: 'قيد المراجعة' },
  { id: 'WDR-2059', userId: 610309, amount: 3.5, method: 'Web3', destination: '0x901c...7d4e', memoTag: 'Polygon', createdAt: '2025-03-07 11:34', status: 'قيد المراجعة' },
 ],
 campaigns: [
  { id: 'CMP-094', userId: 610241, title: 'أدوات العمل عن بعد', platform: 'YouTube', videoUrl: 'https://www.youtube.com/embed/aqz-KE-bpKQ', duration: 40, budget: 32, views: 840, status: 'بانتظار المراجعة' },
  { id: 'CMP-091', userId: 610309, title: 'مراجعة تطبيقات السفر', platform: 'TikTok', videoUrl: 'https://www.youtube.com/embed/ScMzIvxBSi4', duration: 20, budget: 18, views: 1260, status: 'نشطة' },
  { id: 'CMP-088', userId: 610258, title: 'دليل التطبيقات اليومية', platform: 'YouTube', videoUrl: 'https://www.youtube.com/embed/aqz-KE-bpKQ', duration: 40, budget: 7, views: 350, status: 'أوقفتها الميزانية', spent: 7 },
 ],
 proofs: [
  { id: 'PRF-318', userId: 610258, taskId: 'TASK-TG-41', taskType: 'اشتراك قناة', image: proofMock, reward: 0.003, status: 'قيد المراجعة' },
  { id: 'PRF-312', userId: 610411, taskId: 'TASK-TT-09', taskType: 'متابعة TikTok', image: proofMock, reward: 0.003, status: 'قيد المراجعة' },
 ],
 ads: [{ id: 'AD-01', format: 'social', code: '<div class="vr-social">Social placement · demo</div>', enabled: true, updatedAt: '2025-03-06' }, { id: 'AD-02', format: '320x50', code: '<div class="vr-banner">320 × 50 · demo placement</div>', enabled: false, updatedAt: '2025-03-04' }],
 suspicious: [{ id: 'SIG-118', userId: 610411, attempt: 'رصد أدوات المطور + مشاهدة أسرع من المدة المطلوبة', createdAt: '2025-03-08 08:20', status: 'مفتوح' }, { id: 'SIG-112', userId: 610258, attempt: 'عدة حسابات على الجهاز نفسه', createdAt: '2025-03-07 15:10', status: 'مفتوح' }, { id: 'SIG-107', userId: 610309, attempt: 'تلاعب في DOM', createdAt: '2025-03-06 10:22', status: 'تمت المراجعة' }],
 settings: { binanceWithdrawMin: 1, web3WithdrawMin: 2, starsDepositMin: 1, web3DepositMin: 5, userShare: 20, platformShare: 10, durationMin: 10, durationMax: 80, cpmMin: 1.5, cpmMax: 4, telegramCpm: 2.2, tiktokCpm: 2.8, taskReward: 0.003, web3Address: '0x0000...preview', maintenance: false },
 reports: [],
};
const labels: Record<string, string> = { overview:'نظرة عامة', users:'مستخدمو Telegram', deposits:'الإيداعات', withdrawals:'السحوبات', campaigns:'الحملات', proofs:'إثباتات المهام', ads:'مخزون Adstera', settings:'الإعدادات', notifications:'الإشعارات', suspicious:'مستخدمون مشبوهون' };
const cx = (...classes: Array<string | undefined>) => classes.filter(Boolean).join(' ');
const cell = 'px-4 py-1.5 text-right align-middle';
const btn = 'inline-flex items-center justify-center gap-2 rounded-xl px-3 py-2 text-xs font-bold transition hover:-translate-y-px disabled:opacity-40';
const primary = `${btn} bg-[#1557ee] text-white`;
const soft = `${btn} border border-slate-200 bg-white text-slate-700 hover:bg-slate-50`;
function getState(): State { try { const s = localStorage.getItem(KEY); if (!s) return seed; const stored=JSON.parse(s) as Partial<State>; const campaigns=stored.campaigns??seed.campaigns; return { ...seed, ...stored, campaigns:[...campaigns,...seed.campaigns.filter(c=>!campaigns.some(existing=>existing.id===c.id))], settings:{...seed.settings,...stored.settings} }; } catch { return seed; } }
function Field({ label, ...props }: { label: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <label className="grid gap-1.5 text-xs font-bold text-slate-600">{label}<input {...props} className={cx('w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-medium text-slate-800 outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100', props.className)} /></label>; }
function Badge({ children }: { children: React.ReactNode }) { const good = ['نشط','ناجح','معتمد','مفعّل','تمت المراجعة'].includes(String(children)); const bad = ['محظور','فاشل','مرفوض','موقوف'].includes(String(children)); return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold ${good?'bg-emerald-50 text-emerald-700':bad?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700'}`}>{children}</span>; }

export function AdminConsole({ activeScreen, onPageChange }: { activeScreen: string; onPageChange: (page: string) => void }) {
 const [data, setData] = useState<State>(getState);
 const [page, setPage] = useState(() => activeScreen.startsWith('admin-') ? activeScreen.slice(6) : 'overview');
 const [query, setQuery] = useState('');
 const [pageNo, setPageNo] = useState(1);
 const [dialog, setDialog] = useState<{kind:string; id?:string|number}|null>(null);
 const [pendingAction, setPendingAction] = useState<(()=>void)|null>(null);
 const [filter, setFilter] = useState('الكل');
 const [toast, setToast] = useState('');
 useEffect(() => {
  const nextPage = activeScreen.startsWith('admin-') ? activeScreen.slice(6) : 'overview';
  if (nextPage in labels) {
   setPage(nextPage);
   setQuery('');
   setFilter('الكل');
   setPageNo(1);
  }
 }, [activeScreen]);
 useEffect(() => { try { localStorage.setItem(KEY, JSON.stringify(data)); } catch {} }, [data]);
 const navigateToPage = (nextPage: string) => {
  setPage(nextPage);
  setQuery('');
  setFilter('الكل');
  setPageNo(1);
  onPageChange(nextPage);
 };
 const updateRows = (key: keyof State, id: string|number, patch: Record<string, any>) => setData(d => ({...d, [key]: (d[key] as any[]).map(x => x.id===id ? {...x,...patch}:x)}));
 const userBy = (id:number|undefined) => data.users.find(u=>u.id===id);
 const announce = (s:string) => { setToast(s); window.setTimeout(()=>setToast(''),2300); };
 const title = labels[page] || 'نظرة عامة';
 const filteredUsers = data.users.filter(u => !query || [u.id,u.name,u.username].some(v=>String(v).toLowerCase().includes(query.toLowerCase())));
 const pageSize = 100;
 const visibleUsers = filteredUsers.slice((pageNo-1)*pageSize,pageNo*pageSize);
 const rowData = (key: 'deposits'|'withdrawals'|'campaigns'|'proofs'|'suspicious') => data[key].filter(r=>(filter==='الكل'||r.status===filter)&&(!query||[r.id,r.memoTag,r.txId,r.destination,r.title,r.taskId,r.attempt,userBy(r.userId)?.name,userBy(r.userId)?.username].some(x=>String(x??'').toLowerCase().includes(query.toLowerCase()))));
 const search = <div className="relative min-w-0 flex-1"><Search className="absolute right-3 top-3 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>{setQuery(e.target.value);setPageNo(1)}} placeholder="ابحث بالمعرّف أو الاسم أو الوسم…" className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pe-10 ps-3 text-sm outline-none focus:border-blue-400" /></div>;
 const statusSelect = (statuses:string[]) => <select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-bold"><option>الكل</option>{statuses.map(x=><option key={x}>{x}</option>)}</select>;
 const header = <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-1 text-xs font-bold text-[#1557ee]">VIDREWARD / OPERATIONS</div><h1 className="text-2xl font-extrabold tracking-tight text-[#12234b]">{title}</h1></div><span className="rounded-full border border-amber-200 bg-amber-50 px-3 py-2 text-[11px] font-bold text-amber-800">معاينة محلية · لا اتصال بالخادم</span></div>;
 const panel = (children:React.ReactNode, cls='') => <section className={`rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_12px_35px_rgba(18,32,77,.04)] md:p-5 ${cls}`}>{children}</section>;
 const table = (head:string[], rows:React.ReactNode[]) => panel(<div className="-mx-4 overflow-x-auto md:mx-0"><table className="w-full min-w-[680px] border-collapse text-sm"><thead><tr className="border-b border-slate-100 bg-slate-50/80 text-[11px] text-slate-500">{head.map(x=><th className={cell} key={x}>{x}</th>)}</tr></thead><tbody>{rows}</tbody></table></div>);
 const confirm = (message:string, onConfirm:()=>void) => { setPendingAction(()=>onConfirm); setDialog({kind:'confirm', id:message}); };
 const action = (text:string, cb:()=>void, danger=false) => <button onClick={cb} className={`${btn} ${danger?'bg-rose-50 text-rose-700':'bg-slate-100 text-slate-700'}`}>{text}</button>;

 const content = () => {
  if(page==='overview') return <div className="space-y-5">
   <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[
    ['مستخدمون مسجلون',data.users.length,Users],
    ['حملات نشطة',data.campaigns.filter(x=>x.status==='نشطة').length,Megaphone],
    ['حملات أوقفتها الميزانية',data.campaigns.filter(x=>x.status==='أوقفتها الميزانية').length,Activity],
    ['إيداعات ناجحة · USDT',data.deposits.filter(x=>x.status==='ناجح').reduce((sum,x)=>sum+(x.method==='Stars'?Number(x.amount??0)*0.01:Number(x.amount??0)),0).toFixed(2),CircleDollarSign],
    ['إجمالي أرباح الفيديو',data.users.reduce((sum,u)=>sum+u.earnedBalance,0).toFixed(3),Wallet],
    ['مستخدمون حظرهم النظام',data.users.filter(x=>x.bannedBySystem).length,ShieldCheck]
   ].map(([l,v,I]:any)=><div key={l} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><span className="text-xs font-bold text-slate-500">{l}</span><I className="h-5 w-5 text-[#1557ee]"/></div><div className="mt-4 text-3xl font-extrabold text-[#12234b]">{v}</div><div className="mt-2 text-[11px] text-slate-400">بيانات نموذجية على هذا الجهاز</div></div>)}</div>
   {panel(<><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edf3ff] text-[#1557ee]"><ShieldCheck size={20}/></span><div><h2 className="font-extrabold">مركز العمليات</h2><p className="mt-1 text-sm leading-6 text-slate-500">راجع النشاط التجريبي، وطبّق التغييرات محليًا. لا تؤثر أي عملية هنا في حسابات أو أرصدة حقيقية.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{[['طلبات السحب',data.withdrawals.filter(x=>x.status==='قيد المراجعة').length,'withdrawals'],['إثباتات المهام',data.proofs.filter(x=>x.status==='قيد المراجعة').length,'proofs'],['إشارات المخاطر',data.suspicious.filter(x=>x.status==='مفتوح').length,'suspicious'],['تقارير الإرسال',data.reports.length,'notifications']].map(([a,b,c])=><button key={c} onClick={()=>navigateToPage(String(c))} className="flex items-center justify-between rounded-xl bg-[#f7f9fc] p-4 text-right"><span className="text-sm font-bold">{a}</span><span className="font-mono text-lg font-bold text-[#1557ee]">{b}</span></button>)}</div></>)}
  </div>;
  if(page==='users') return <div className="space-y-4">{panel(<div className="flex flex-wrap gap-3">{search}<span className="self-center text-xs text-slate-400">حد أقصى 100 مستخدم في الصفحة</span></div>)}{table(['المستخدم','Telegram ID','رصيد المعلن','الأرباح','الحالة','آخر نشاط',''],visibleUsers.map(u=><tr key={u.id} className="border-b border-slate-50 hover:bg-slate-50/70"><td className={cell}><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf3ff] text-xs font-extrabold text-[#1557ee]">{u.avatar}</span><div><b>{u.name}</b><div className="text-xs text-slate-400">@{u.username}</div></div></div></td><td className={`${cell} font-mono`}>{u.id}</td><td className={`${cell} font-mono`}>{u.advertiserBalance.toFixed(2)} $</td><td className={`${cell} font-mono`}>{u.earnedBalance.toFixed(3)} $</td><td className={cell}><Badge>{u.status}</Badge></td><td className={cell}>{u.lastActive}</td><td className={cell}><button className={soft} onClick={()=>setDialog({kind:'user',id:u.id})}>التفاصيل</button></td></tr>))}{panel(<div className="flex items-center justify-between text-xs text-slate-500"><span>{filteredUsers.length} مستخدم</span><div className="flex gap-2"><button className={soft} disabled={pageNo<=1} onClick={()=>setPageNo(n=>n-1)}>السابق</button><span className="px-2 py-2">صفحة {pageNo} / {Math.max(1,Math.ceil(filteredUsers.length/pageSize))}</span><button className={soft} disabled={pageNo>=Math.ceil(filteredUsers.length/pageSize)} onClick={()=>setPageNo(n=>n+1)}>التالي</button></div></div>)}</div>;
  if(page==='deposits') return <div className="space-y-4">{panel(<div className="flex flex-wrap gap-3">{search}{statusSelect(['ناجح','فاشل'])}</div>)}{table(['العملية / المعاملة','المستخدم','الطريقة','المبلغ','Memo / Tag','المحفظة','الحالة / الوقت'],rowData('deposits').map(r=><tr key={r.id} className="border-b border-slate-50"><td className={cell}><b>{r.id}</b><div className="text-[11px] text-slate-400">{r.txId}</div></td><td className={cell}>{userBy(r.userId)?.name}</td><td className={cell}>{r.method}</td><td className={`${cell} font-mono`}>{r.amount} {r.method==='Stars'?'XTR':'USDT'}</td><td className={`${cell} font-mono`}>{r.memoTag}</td><td className={`${cell} font-mono`}>{r.wallet||'—'}</td><td className={cell}><Badge>{r.status}</Badge><div className="mt-1 text-[10px] text-slate-400">{r.createdAt}</div>{r.reason&&<div className="mt-1 max-w-40 text-[10px] text-rose-600">{r.reason}</div>}</td></tr>))}</div>;
  if(page==='withdrawals') return <div className="space-y-4">{panel(<div className="flex gap-3">{search}{statusSelect(['قيد المراجعة','معتمد','مرفوض'])}</div>)}{table(['الطلب','المستخدم','القناة','المبلغ','الوجهة','Memo','التاريخ','الإجراء'],rowData('withdrawals').map(r=><tr key={r.id} className="border-b border-slate-50"><td className={cell}><b>{r.id}</b></td><td className={cell}>{userBy(r.userId)?.name}</td><td className={cell}>{r.method}</td><td className={cell}><button className="inline-flex items-center gap-1 font-mono" aria-label="نسخ المبلغ" onClick={()=>{navigator.clipboard?.writeText(`${r.amount} USDT`);announce('تم نسخ المبلغ')}}>{r.amount} USDT<Copy size={13}/></button></td><td className={cell}><div className="flex items-center gap-1 font-mono"><span dir="ltr">{r.destination}</span><button aria-label="نسخ الوجهة" onClick={()=>{navigator.clipboard?.writeText(r.destination);announce('تم النسخ')}}><Copy size={14}/></button></div></td><td className={cell}><button onClick={()=>{navigator.clipboard?.writeText(r.memoTag);announce('تم النسخ')}} className="flex items-center gap-1 font-mono">{r.memoTag}<Copy size={13}/></button></td><td className={cell}>{r.createdAt}</td><td className={cell}>{r.status==='قيد المراجعة'?<div className="flex gap-1">{action('اعتماد',()=>{updateRows('withdrawals',r.id,{status:'معتمد'});announce('تم اعتماد الطلب محليًا')})}{action('رفض',()=>confirm('رفض طلب السحب؟',()=>{updateRows('withdrawals',r.id,{status:'مرفوض'});setDialog(null)}),true)}</div>:<Badge>{r.status}</Badge>}</td></tr>))}</div>;
  if(page==='campaigns') return <div className="space-y-4">{panel(<div className="flex gap-3">{search}{statusSelect(['بانتظار المراجعة','نشطة','موقوفة','مرفوضة','أوقفتها الميزانية'])}</div>)}{table(['الحملة','المستخدم','المنصة','المدة','الميزانية','المشاهدات','الحالة','مراجعة'],rowData('campaigns').map(r=><tr key={r.id} className="border-b border-slate-50"><td className={cell}><b>{r.title}</b><div className="text-xs text-slate-400">{r.id}</div></td><td className={cell}>{userBy(r.userId)?.name}</td><td className={cell}>{r.platform}</td><td className={cell}>{r.duration} ث</td><td className={cell}>{r.budget} USDT</td><td className={cell}>{r.views.toLocaleString()}</td><td className={cell}><Badge>{r.status}</Badge></td><td className={cell}><button className={soft} onClick={()=>setDialog({kind:'campaign',id:r.id})}>فيديو وإجراءات</button></td></tr>))}</div>;
  if(page==='proofs') return <div className="space-y-4">{panel(<div className="flex gap-3">{search}{statusSelect(['قيد المراجعة','معتمد','مرفوض'])}</div>)}{table(['الإثبات','المستخدم','المهمة','المكافأة','الحالة','المرفق','الإجراء'],rowData('proofs').map(r=><tr key={r.id} className="border-b border-slate-50"><td className={cell}>{r.id}</td><td className={cell}>{userBy(r.userId)?.name}</td><td className={cell}>{r.taskId}<div className="text-xs text-slate-400">{r.taskType}</div></td><td className={cell}>{r.reward} USDT</td><td className={cell}><Badge>{r.status}</Badge></td><td className={cell}><button className={soft} onClick={()=>setDialog({kind:'proof',id:r.id})}>عرض الصورة</button></td><td className={cell}>{r.status==='قيد المراجعة'?<div className="flex gap-1">{action('اعتماد المكافأة',()=>{setData(d=>{const p=d.proofs.find(x=>x.id===r.id);if(!p||p.status!=='قيد المراجعة')return d;return {...d,proofs:d.proofs.map(x=>x.id===r.id?{...x,status:'معتمد'}:x),users:d.users.map(u=>u.id===p.userId?{...u,earnedBalance:Number((u.earnedBalance+p.reward).toFixed(6))}:u)}});announce('تم اعتماد الإثبات وإضافة المكافأة محليًا')})}{action('رفض',()=>setDialog({kind:'reject-proof',id:r.id}),true)}</div>:r.rejectionReason||<Badge>{r.status}</Badge>}</td></tr>))}</div>;
  if(page==='ads') return <div className="space-y-4">{panel(<div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">أكواد Adstera</h2><p className="mt-1 text-xs text-slate-500">تظهر الشيفرة كمصدر نصي غير منفّذ؛ المعاينة معزولة ولا تحمل الشيفرة.</p></div><button className={primary} onClick={()=>setDialog({kind:'ad-new'})}>إضافة كود</button></div>)}{data.ads.map(ad=>panel(<div key={ad.id} className="grid gap-4 md:grid-cols-[1fr_260px]"><div><div className="flex items-center justify-between"><div><b>{ad.format==='social'?'Social':'320 × 50'} placement</b><div className="mt-1 text-xs text-slate-400">تم التحديث {ad.updatedAt}</div></div><button onClick={()=>updateRows('ads',ad.id,{enabled:!ad.enabled})}><Badge>{ad.enabled?'مفعّل':'معطّل'}</Badge></button></div><textarea aria-label="مصدر الإعلان" value={ad.code} onChange={e=>updateRows('ads',ad.id,{code:e.target.value,updatedAt:new Date().toISOString().slice(0,10)})} rows={4} className="mt-3 w-full rounded-xl bg-[#101b32] p-3 font-mono text-xs text-emerald-100 outline-none"/></div><div className="rounded-xl border border-dashed border-slate-300 bg-[#f7f9fc] p-3"><div className="mb-2 flex items-center gap-2 text-xs font-bold"><Eye size={14}/> معاينة غير تنفيذية</div><div className="grid min-h-24 place-items-center rounded-lg bg-white px-3 text-center text-xs text-slate-500">{ad.format==='320x50'?'مساحة 320 × 50': 'بطاقة موضع اجتماعي'}<span className="mt-1 block font-mono text-[9px]">المصدر غير محمّل</span></div><button className={`${soft} mt-2 w-full`} onClick={()=>setDialog({kind:'ad-edit',id:ad.id})}>تعديل الكود</button></div></div>))}</div>;
  if(page==='settings') return <SettingsPanel values={data.settings} onSave={v=>{setData(d=>({...d,settings:v}));announce('تم حفظ الإعدادات محليًا')}}/>;
  if(page==='notifications') return <NotificationPanel reports={data.reports} onSend={r=>{setData(d=>({...d,reports:[{...r,id:`NTF-${Date.now()}`,createdAt:new Date().toLocaleString('ar'),status:'مسودة محلية'},...d.reports]}));announce('حُفظ التقرير محليًا؛ الإرسال المباشر غير متصل')}}/>;
  return <div className="space-y-4">{panel(<div className="flex gap-3">{search}{statusSelect(['مفتوح','تمت المراجعة'])}</div>)}{table(['الإشارة','المستخدم','نوع الإشارة','الوقت','الحالة','الإجراء'],rowData('suspicious').map(r=><tr key={r.id} className="border-b border-slate-50"><td className={cell}>{r.id}</td><td className={cell}>{userBy(r.userId)?.name} · {r.userId}</td><td className={cell}>{r.attempt}</td><td className={cell}>{r.createdAt}</td><td className={cell}><Badge>{r.status}</Badge></td><td className={cell}>{action('حظر المستخدم',()=>confirm('حظر هذا المستخدم؟',()=>{setData(d=>({...d,users:d.users.map(u=>u.id===r.userId?{...u,status:'محظور'}:u),suspicious:d.suspicious.map(x=>x.id===r.id?{...x,status:'تمت المراجعة'}:x)}));setDialog(null)}),true)}</td></tr>))}</div>;
 };

 return <main dir="rtl" className="min-h-[100dvh] bg-[#f7f9fc] px-3 pb-28 pt-5 text-[#12234b] sm:px-6 lg:px-8">
  <div className="mx-auto max-w-[1440px]">{header}
   <div className="mb-4 flex items-start gap-3 rounded-xl border border-amber-200 bg-[#fff9eb] px-4 py-3 text-xs leading-5 text-amber-900"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/><span><b>وضع المعاينة:</b> بيانات تجريبية خيالية محفوظة على هذا الجهاز. لا تؤثر العمليات على مستخدمين أو أموال أو Telegram أو مواضع إعلانية حقيقية.</span></div>
    <div className="mt-5">{content()}</div>
   <footer className="mt-5 text-center text-[10px] text-slate-400">VidReward Admin · نسخة تجريبية محلية · لا اتصال بخدمات الإنتاج</footer>
  </div>
  {toast&&<div role="status" className="fixed bottom-20 right-4 z-[110] rounded-xl bg-[#12234b] px-4 py-3 text-sm font-bold text-white shadow-xl">{toast}</div>}
  {dialog&&<Dialog dialog={dialog} data={data} userBy={userBy} onClose={()=>setDialog(null)} onConfirmAction={()=>{pendingAction?.();setPendingAction(null);setDialog(null);announce('تم تطبيق الإجراء محليًا')}} onConfirm={(id,patch)=>{if(dialog.kind==='user-edit'||dialog.kind==='user'){setData(d=>({...d,users:d.users.map(u=>u.id===id?{...u,...patch}:u)}))}else if(dialog.kind==='ad-new'){setData(d=>({...d,ads:[{id:`AD-${Date.now()}`,format:patch.format,code:patch.code,enabled:false,updatedAt:new Date().toISOString().slice(0,10)},...d.ads]}))}else if(dialog.kind==='ad-edit'){updateRows('ads',id as string,patch)}else if(dialog.kind==='reject-proof'){updateRows('proofs',id as string,patch)}else if(dialog.kind==='campaign'){updateRows('campaigns',id as string,patch)}setDialog(null);announce('تم حفظ التغيير محليًا')}} onDelete={id=>{setData(d=>({...d,users:d.users.filter(u=>u.id!==id)}));setDialog(null)}} onAction={cb=>{confirm('تأكيد الإجراء؟',cb)}}/>}
 </main>;
}

function SettingsPanel({values,onSave}:{values:Record<string,any>;onSave:(v:Record<string,any>)=>void}) {
 const [v,setV]=useState(values); useEffect(()=>setV(values),[values]);
 const fields:[string,string][]=[['binanceWithdrawMin','الحد الأدنى للسحب عبر Binance (USDT)'],['web3WithdrawMin','الحد الأدنى للسحب عبر Web3 (USDT)'],['starsDepositMin','الحد الأدنى للإيداع عبر Stars'],['web3DepositMin','الحد الأدنى للإيداع عبر Web3 (USDT)'],['userShare','حصة المستخدم من الإيراد (%)'],['platformShare','حصة المنصة (%)'],['durationMin','أقصر مدة فيديو (ثانية)'],['durationMax','أطول مدة فيديو (ثانية)'],['cpmMin','أقل CPM'],['cpmMax','أعلى CPM'],['telegramCpm','CPM إعلانات Telegram'],['tiktokCpm','CPM إعلانات TikTok'],['taskReward','مكافأة مهمة Telegram الثابتة'],['web3Address','عنوان Web3']];
 return <div className="space-y-4">{<section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-extrabold">ضوابط المنصة</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{fields.map(([key,label])=><Field key={key} label={label} type={key==='web3Address'?'text':'number'} step="any" value={v[key]} onChange={e=>setV({...v,[key]:key==='web3Address'?e.target.value:Number(e.target.value)})}/>)}</div><label className="mt-5 flex items-center gap-3 rounded-xl bg-[#fff9eb] p-4 text-sm font-bold"><input type="checkbox" checked={v.maintenance} onChange={e=>setV({...v,maintenance:e.target.checked})}/> وضع الصيانة (محلي فقط)</label><button className={`${primary} mt-4`} onClick={()=>onSave(v)}>حفظ الإعدادات</button></section>}<p className="text-xs text-slate-400">تغييرات المعاينة لا تصل إلى الخادم أو البوت.</p></div>;
}

function NotificationPanel({reports,onSend}:{reports:Row[];onSend:(r:Omit<Row,'id'>)=>void}) {
 const [title,setTitle]=useState('');const [body,setBody]=useState('');const [buttonTitle,setButtonTitle]=useState('');const [link,setLink]=useState('');
 return <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(300px,.8fr)]"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-extrabold">إنشاء إشعار</h2><div className="grid gap-4"><Field label="العنوان العريض" value={title} onChange={e=>setTitle(e.target.value)} placeholder="عنوان الإشعار"/><label className="grid gap-1.5 text-xs font-bold text-slate-600">النص<textarea value={body} onChange={e=>setBody(e.target.value)} rows={5} className="rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-400"/></label><div className="grid gap-3 sm:grid-cols-2"><Field label="عنوان الزر (اختياري)" value={buttonTitle} onChange={e=>setButtonTitle(e.target.value)}/><Field label="رابط الزر (اختياري)" value={link} onChange={e=>setLink(e.target.value)}/></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-900">لا يوجد اتصال بالخادم، لذلك لا يمكن إرسال الإشعارات فعليًا. زر الإرسال الجماعي معطل بوضوح؛ يمكنك حفظ نسخة محلية للمعاينة فقط.</div><button type="button" disabled title="يتطلب اتصال خادم غير متاح" className={`${btn} w-full cursor-not-allowed border border-slate-200 bg-slate-100 text-slate-400`}>إرسال إلى جميع المستخدمين · غير متاح</button><button className={primary} disabled={!title.trim()||!body.trim()} onClick={()=>{onSend({title,body,buttonTitle,link});setTitle('');setBody('')}}>حفظ كتقرير معاينة</button></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-extrabold">سجل التسليم المحلي</h2><div className="space-y-3">{reports.length?reports.map(r=><div key={r.id} className="rounded-xl bg-[#f7f9fc] p-3"><div className="flex justify-between gap-2"><b className="text-sm">{r.title}</b><Badge>{r.status}</Badge></div><p className="mt-1 text-xs text-slate-500">{r.body}</p><div className="mt-2 text-[10px] text-slate-400">{r.createdAt} · لم يتم الإرسال إلى Telegram</div></div>):<p className="rounded-xl bg-[#f7f9fc] p-5 text-center text-sm text-slate-400">لا توجد تقارير محفوظة</p>}</div></section></div>;
}

function Dialog({dialog,data,userBy,onClose,onConfirm,onConfirmAction,onDelete,onAction}:{dialog:{kind:string;id?:string|number};data:State;userBy:(id:number|undefined)=>User|undefined;onClose:()=>void;onConfirm:(id:any,patch:any)=>void;onConfirmAction:()=>void;onDelete:(id:number)=>void;onAction:(cb:()=>void)=>void}) {
 const [values,setValues]=useState<Record<string,any>>({}); const user=dialog.kind==='user'||dialog.kind==='user-edit'?userBy(Number(dialog.id)):undefined;
 const campaign=data.campaigns.find(x=>x.id===dialog.id);const proof=data.proofs.find(x=>x.id===dialog.id);const ad=data.ads.find(x=>x.id===dialog.id);
 useEffect(()=>{if(user)setValues({...user});if(ad)setValues({...ad})},[dialog.id]);
 const field=(key:string,label:string,type='text')=><Field label={label} type={type} value={values[key]??''} onChange={e=>setValues(v=>({...v,[key]:type==='number'?Number(e.target.value):e.target.value}))}/>;
 const save=(patch=values)=>onConfirm(dialog.id,patch);
 let content:React.ReactNode=null;let heading='تفاصيل';
 if(dialog.kind==='user'||dialog.kind==='user-edit'){heading='ملف المستخدم';content=user&&<div className="space-y-3"><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><small>معرّف Telegram</small><div className="font-mono font-bold">{user.id}</div></div><div className="rounded-xl bg-slate-50 p-3"><small>الحالة</small><div><Badge>{user.status}</Badge></div></div></div><div className="grid gap-3 sm:grid-cols-2">{field('name','الاسم')}{field('username','اسم المستخدم')}{field('advertiserBalance','رصيد المعلن','number')}{field('earnedBalance','الأرباح','number')}</div><div className="grid grid-cols-2 gap-3 text-xs"><p>تاريخ التسجيل<br/><b>{user.joinedAt}</b></p><p>آخر تسجيل دخول<br/><b>{user.lastLogin}</b></p><p>آخر نشاط<br/><b>{user.lastActive}</b></p><p>دُعي بواسطة<br/><b>{user.invitedBy}</b></p></div><div className="flex flex-wrap gap-2"><button className={primary} onClick={()=>save()}>حفظ التعديلات والأرصدة</button><button className={soft} onClick={()=>onAction(()=>save({status:user.status==='نشط'?'محظور':'نشط'}))}>{user.status==='نشط'?'حظر':'إلغاء الحظر'}</button><button className={`${btn} bg-rose-50 text-rose-700`} onClick={()=>onAction(()=>onDelete(user.id))}><Trash2 size={14}/> حذف</button></div></div>}
 else if(dialog.kind==='campaign'){heading='مراجعة الفيديو';content=campaign&&<div className="space-y-3"><div className="aspect-video overflow-hidden rounded-xl bg-slate-900"><iframe title="معاينة فيديو الحملة" className="h-full w-full" src={campaign.videoUrl} allow="encrypted-media; picture-in-picture" referrerPolicy="strict-origin-when-cross-origin"/></div><h3 className="font-bold">{campaign.title}</h3><div className="grid grid-cols-2 gap-2 text-xs text-slate-500"><span>النوع: {campaign.platform}</span><span>المدة: {campaign.duration} ثانية</span><span>الميزانية: {campaign.budget} USDT</span><span>المشاهدات: {campaign.views}</span></div><div className="flex flex-wrap gap-2">{['نشطة','مرفوضة','موقوفة'].map(status=><button key={status} className={status==='مرفوضة'?`${btn} bg-rose-50 text-rose-700`:soft} onClick={()=>status==='مرفوضة'?onAction(()=>save({status})):save({status})}>{status==='نشطة'?'اعتماد':status==='مرفوضة'?'رفض':'إيقاف مؤقت'}</button>)}</div></div>}
 else if(dialog.kind==='proof'){heading='صورة إثبات المهمة';content=proof&&<div><img src={proof.image} alt="صورة الإثبات" className="max-h-[60vh] w-full rounded-xl object-contain"/><p className="mt-3 text-xs text-slate-500">{userBy(proof.userId)?.name} · {proof.taskId}</p></div>}
 else if(dialog.kind==='reject-proof'){heading='رفض الإثبات';content=<div className="space-y-3"><label className="grid gap-1.5 text-xs font-bold">سبب الرفض<textarea value={values.reason??''} onChange={e=>setValues({...values,reason:e.target.value})} rows={3} className="rounded-xl border border-slate-200 p-3"/></label><button className={`${btn} bg-rose-600 text-white`} onClick={()=>onAction(()=>save({status:'مرفوض',rejectionReason:values.reason||'لم يطابق الإثبات المتطلبات'}))}>رفض الإثبات</button></div>}
 else if(dialog.kind==='ad-new'||dialog.kind==='ad-edit'){heading=dialog.kind==='ad-new'?'إضافة موضع إعلاني':'تعديل الشيفرة';content=<div className="space-y-3"><label className="grid gap-1.5 text-xs font-bold">التنسيق<select value={values.format??'social'} onChange={e=>setValues({...values,format:e.target.value})} className="rounded-xl border p-3"><option value="social">Social</option><option value="320x50">320 × 50</option></select></label><label className="grid gap-1.5 text-xs font-bold">مصدر الكود غير المنفذ<textarea value={values.code??''} onChange={e=>setValues({...values,code:e.target.value})} rows={6} className="rounded-xl bg-[#101b32] p-3 font-mono text-xs text-emerald-100"/></label><p className="text-xs text-amber-700">لن يتم تنفيذ هذا المحتوى أو تحميله في المعاينة.</p><button className={primary} onClick={()=>save()}>حفظ الكود</button></div>}
 else {heading='تأكيد الإجراء';content=<div className="space-y-4"><p className="text-sm">{dialog.id}</p><p className="text-xs text-slate-500">سيُطبّق هذا الإجراء على بيانات المعاينة المحلية فقط.</p><div className="flex gap-2"><button className={`${btn} bg-rose-600 text-white`} onClick={onConfirmAction}>تأكيد</button><button className={soft} onClick={onClose}>إلغاء</button></div></div>}
 const userFullPage=dialog.kind==='user'||dialog.kind==='user-edit';
 return <div className={`fixed inset-0 z-[100] flex justify-center bg-[#061333]/45 backdrop-blur-sm ${userFullPage?'items-stretch p-0 sm:items-center sm:p-4':'items-end p-0 sm:items-center sm:p-4'}`} onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section role="dialog" aria-modal="true" className={`${userFullPage?'h-[100dvh] w-full max-w-none rounded-none sm:h-auto sm:max-h-[92dvh] sm:max-w-xl sm:rounded-3xl':'max-h-[92dvh] w-full max-w-xl rounded-t-3xl sm:rounded-3xl'} overflow-y-auto bg-white p-5 shadow-2xl`}><header className="mb-4 flex items-center justify-between"><h2 className="font-extrabold">{heading}</h2><button aria-label="إغلاق" onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100"><X size={18}/></button></header>{content}</section></div>;
}